name: Deploying Frontend to Staging

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: reharvest
  EC2_USERNAME: ubuntu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # ✅ Corrected

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Stopping existing container..."
            sudo docker stop ${{ env.DOCKER_IMAGE_NAME }} || true
            sudo docker rm ${{ env.DOCKER_IMAGE_NAME }} || true

            echo "Removing old image..."
            sudo docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest || true

            echo "Pulling new image..."
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

            echo "Starting new container..."
            sudo docker run -d \
              --name ${{ env.DOCKER_IMAGE_NAME }} \
              -p 3000:3000 \
              --restart unless-stopped \
              ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

            echo "Verifying deployment..."
            sudo docker ps

            echo "Deployment successful."
